name: dask-binder-template
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask=2.26.0
  # JupyterLab extensions
  - nodejs
  - jupyterlab>=2.0.0
  - dask-labextension>=2.0.0
  - ipywidgets